import { env } from 'cloudflare:workers';
import type { Book, BookDraft } from '@/types/book';

const schema = `CREATE TABLE IF NOT EXISTS books (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,author TEXT NOT NULL,author_first_name TEXT NOT NULL DEFAULT '',author_last_name TEXT NOT NULL DEFAULT '',code TEXT NOT NULL DEFAULT '',code_type TEXT NOT NULL DEFAULT '',genres TEXT NOT NULL DEFAULT '[]',publisher TEXT NOT NULL DEFAULT '',publication_year INTEGER,saga TEXT NOT NULL DEFAULT '',saga_order INTEGER,prequel TEXT NOT NULL DEFAULT '',sequel TEXT NOT NULL DEFAULT '',cover_url TEXT,plot TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',rating INTEGER NOT NULL DEFAULT 0,is_read INTEGER NOT NULL DEFAULT 0,in_library INTEGER NOT NULL DEFAULT 0,lent_to TEXT NOT NULL DEFAULT '',lent_date TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`;
const indexes = [`CREATE INDEX IF NOT EXISTS idx_books_author ON books(author_last_name,author_first_name)`,`CREATE INDEX IF NOT EXISTS idx_books_saga ON books(saga,saga_order)`,`CREATE INDEX IF NOT EXISTS idx_books_code ON books(code)`];
const cols = `id,title,author,author_first_name authorFirstName,author_last_name authorLastName,code,code_type codeType,genres,publisher,publication_year publicationYear,saga,saga_order sagaOrder,prequel,sequel,cover_url coverUrl,plot,notes,rating,is_read isRead,in_library inLibrary,lent_to lentTo,lent_date lentDate`;
const fieldMap = new Map(Object.entries({title:'title',author:'author',authorFirstName:'author_first_name',authorLastName:'author_last_name',code:'code',codeType:'code_type',genres:'genres',publisher:'publisher',publicationYear:'publication_year',saga:'saga',sagaOrder:'saga_order',prequel:'prequel',sequel:'sequel',coverUrl:'cover_url',plot:'plot',notes:'notes',rating:'rating',isRead:'is_read',inLibrary:'in_library',lentTo:'lent_to',lentDate:'lent_date'}));
function binding(){ if(!env.DB) throw new Error('Database non disponibile'); return env.DB; }
async function ready(){ const db=binding(); await db.prepare(schema).run(); await db.batch(indexes.map((sql)=>db.prepare(sql))); }
function row(value:Record<string,unknown>):Book{return {...value,genres:JSON.parse(String(value.genres||'[]')),isRead:Boolean(value.isRead),inLibrary:Boolean(value.inLibrary)} as Book;}
export async function allBooks(){await ready();const result=await binding().prepare(`SELECT ${cols} FROM books ORDER BY author_last_name,author_first_name,saga,saga_order,title`).all();return (result.results as Record<string,unknown>[]).map(row);}
export async function insertBook(book:BookDraft){await ready();const now=new Date().toISOString();const result=await binding().prepare(`INSERT INTO books(title,author,author_first_name,author_last_name,code,code_type,genres,publisher,publication_year,saga,saga_order,prequel,sequel,cover_url,plot,notes,rating,is_read,in_library,lent_to,lent_date,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING ${cols}`).bind(book.title,book.author,book.authorFirstName,book.authorLastName,book.code,book.codeType,JSON.stringify(book.genres),book.publisher,book.publicationYear,book.saga,book.sagaOrder,book.prequel,book.sequel,book.coverUrl,book.plot,book.notes,book.rating,book.isRead?1:0,book.inLibrary?1:0,book.lentTo,book.lentDate,now,now).first<Record<string,unknown>>();return row(result!);}
export async function patchBook(id:number,patch:Partial<BookDraft>){await ready();const entries=Object.entries(patch).filter(([key])=>fieldMap.has(key));if(!entries.length)throw new Error('Nessuna modifica');const values=entries.map(([key,value])=>key==='genres'?JSON.stringify(value??[]):key==='isRead'||key==='inLibrary'?value?1:0:value);const setters=entries.map(([key])=>`${fieldMap.get(key)}=?`);setters.push('updated_at=?');values.push(new Date().toISOString(),id);const result=await binding().prepare(`UPDATE books SET ${setters.join(',')} WHERE id=? RETURNING ${cols}`).bind(...values).first<Record<string,unknown>>();if(!result)throw new Error('Libro non trovato');return row(result);}
export async function removeBook(id:number){await ready();await binding().prepare('DELETE FROM books WHERE id=?').bind(id).run();}
