type Candidate={title:string;author:string;authorFirstName:string;authorLastName:string;code:string;codeType:string;genres:string[];publisher:string;publicationYear:number|null;saga:string;sagaOrder:number|null;prequel:string;sequel:string;coverUrl:string|null;plot:string;notes:string;rating:number;isRead:boolean;inLibrary:boolean;lentTo:string;lentDate:string;source:string};
const literaryGenres:Record<string,string>={fiction:'Narrativa',fantasy:'Fantasy',romance:'Romanzo rosa',mystery:'Giallo',thriller:'Thriller',horror:'Horror',historical:'Romanzo storico',crime:'Crime',classics:'Classici',poetry:'Poesia',biography:'Biografia',autobiography:'Autobiografia',memoir:'Memorie',adventure:'Avventura',sciencefiction:'Fantascienza',dystopia:'Distopia',paranormal:'Paranormale',suspense:'Suspense',comics:'Fumetti',manga:'Manga',humor:'Umorismo',youngadult:'Young adult'};
const clean=(value:unknown)=>String(value??'').replace(/<[^>]*>/g,' ').replace(/https?:\/\/\S+/g,'').replace(/\s+/g,' ').trim();
const plot=(value:unknown)=>clean(value).split(/(?:Recension[ei]|Film|Serie TV|Prezzo|Acquista|Spedizione|Disponibil)/i)[0].trim();
const detect=(value:string)=>{const code=value.replace(/[\s-]/g,'').toUpperCase();if(/^\d{4}-?\d{3}[\dX]$/.test(value)||/^\d{7}[\dX]$/.test(code))return'ISSN';if(/^(\d{9}[\dX]|\d{13})$/.test(code))return'ISBN';return'CODICE A BARRE';};
const names=(author:string)=>{const parts=author.split(/\s+/).filter(Boolean);return{authorFirstName:parts.slice(0,-1).join(' '),authorLastName:parts.at(-1)||author};};
const genres=(values:unknown)=>{const input=Array.isArray(values)?values:[values];const found=new Set<string>();for(const raw of input){const key=clean(raw).toLowerCase().replace(/[^a-z]/g,'');for(const[source,target]of Object.entries(literaryGenres))if(key.includes(source))found.add(target);}return[...found];};
const scalar=(value:unknown)=>Array.isArray(value)?value[0]:value;
const person=(value:unknown)=>{const item=scalar(value);return typeof item==='object'&&item?clean((item as Record<string,unknown>).name):clean(item);};
function nodes(value:unknown):Record<string,unknown>[] {if(Array.isArray(value))return value.flatMap(nodes);if(!value||typeof value!=='object')return[];const obj=value as Record<string,unknown>;return[obj,...Object.values(obj).flatMap(nodes)];}
function jsonLd(html:string){const blocks=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];return blocks.flatMap((match)=>{try{return nodes(JSON.parse(match[1]));}catch{return[];}});}
function candidatesFrom(html:string,source:string,requestedCode:string,codeType:string):Candidate[]{const output:Candidate[]=[];for(const item of jsonLd(html)){const type=clean(item['@type']);if(!/(Book|Product)/i.test(type))continue;const title=clean(item.name||item.headline);const author=person(item.author||item.creator||item.brand);if(!title||!author)continue;const date=clean(item.datePublished||item.releaseDate);const series=typeof item.isPartOf==='object'&&item.isPartOf?clean((item.isPartOf as Record<string,unknown>).name):'';const imageValue=scalar(item.image);const coverUrl=typeof imageValue==='object'&&imageValue?clean((imageValue as Record<string,unknown>).url):clean(imageValue);output.push({title,author,...names(author),code:clean(item.isbn||item.sku||requestedCode),codeType,genres:genres(item.genre||item.category),publisher:person(item.publisher||item.brand),publicationYear:Number(date.match(/\d{4}/)?.[0])||null,saga:series,sagaOrder:null,prequel:'',sequel:'',coverUrl:coverUrl||null,plot:plot(item.description),notes:'',rating:0,isRead:false,inLibrary:false,lentTo:'',lentDate:'',source});}return output;}
async function page(url:string){try{const response=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; LibriDiCarta/1.0)'},signal:AbortSignal.timeout(9000)});return response.ok?await response.text():'';}catch{return'';}}
async function source(url:string,name:string,query:string,type:string){return candidatesFrom(await page(url),name,query,type);}
function merge(primary:Candidate,secondary:Candidate){return{...secondary,...primary,genres:primary.genres.length?primary.genres:secondary.genres,publisher:primary.publisher||secondary.publisher,publicationYear:primary.publicationYear||secondary.publicationYear,saga:primary.saga||secondary.saga,prequel:primary.prequel||secondary.prequel,sequel:primary.sequel||secondary.sequel,coverUrl:primary.coverUrl||secondary.coverUrl,plot:primary.plot||secondary.plot,source:`${primary.source} + ${secondary.source}`};}

export async function GET(request:Request){const query=new URL(request.url).searchParams.get('q')?.trim()||'';if(!query)return Response.json({error:'Inserisci un codice'},{status:400});const type=detect(query);const goodreads=await source(`https://www.goodreads.com/search?q=${encodeURIComponent(query)}`,'Goodreads',query,type);let results=goodreads;
  const title=goodreads[0]?.title||query;const story=await source(`https://app.thestorygraph.com/browse?search_term=${encodeURIComponent(title)}`,'The StoryGraph',query,type);if(results.length&&story.length)results=[merge(results[0],story[0]),...results.slice(1)];else if(!results.length)results=story;
  if(!results.length||results.some((item)=>!item.plot||!item.coverUrl||!item.publisher)){const fallbacks=await Promise.all([
    source(`https://www.ibs.it/search/?query=${encodeURIComponent(query)}`,'IBS',query,type),
    source(`https://www.lafeltrinelli.it/search?query=${encodeURIComponent(query)}`,'Feltrinelli',query,type),
    source(`https://www.mondadoristore.it/search/?g=${encodeURIComponent(query)}`,'Mondadori Store',query,type),
  ]);const additional=fallbacks.flat();if(results.length&&additional.length)results=[merge(results[0],additional[0]),...results.slice(1),...additional.slice(1)];else results=[...results,...additional];}
  const seen=new Set<string>();results=results.filter((item)=>{const key=`${item.title.toLowerCase()}|${item.author.toLowerCase()}|${item.code}`;if(seen.has(key))return false;seen.add(key);return true;}).slice(0,8);
  return Response.json({codeType:type,candidates:results});}
