type Candidate={title:string;author:string;authorFirstName:string;authorLastName:string;code:string;codeType:string;genres:string[];publisher:string;publicationYear:number|null;saga:string;sagaOrder:number|null;prequel:string;sequel:string;coverUrl:string|null;plot:string;notes:string;rating:number;isRead:boolean;inLibrary:boolean;lentTo:string;lentDate:string;source:string};
const literaryGenres:Record<string,string>={fiction:'Narrativa',narrativa:'Narrativa',fantasy:'Fantasy',romance:'Romanzo rosa',rosa:'Romanzo rosa',erotica:'Romanzo rosa',mystery:'Giallo',gialli:'Giallo',thriller:'Thriller',horror:'Horror',historical:'Romanzo storico',storica:'Romanzo storico',crime:'Crime',classics:'Classici',classici:'Classici',poetry:'Poesia',poesia:'Poesia',biography:'Biografia',biografia:'Biografia',autobiography:'Autobiografia',autobiografia:'Autobiografia',memoir:'Memorie',adventure:'Avventura',avventura:'Avventura',sciencefiction:'Fantascienza',fantascienza:'Fantascienza',dystopia:'Distopia',distopia:'Distopia',paranormal:'Paranormale',suspense:'Suspense',comics:'Fumetti',fumetti:'Fumetti',manga:'Manga',humor:'Umorismo',youngadult:'Young adult'};
const catalogCorrections:Record<string,Partial<Candidate>>={'9788804769828':{saga:'Twisted',sagaOrder:1,prequel:'',sequel:'Twisted Games'},'9788804769835':{saga:'Twisted',sagaOrder:2,prequel:'Twisted Love',sequel:'Twisted Hate'},'9788804769842':{saga:'Twisted',sagaOrder:3,prequel:'Twisted Games',sequel:'Twisted Lies'}};
const clean=(value:unknown)=>String(value??'').replace(/<[^>]*>/g,' ').replace(/https?:\/\/\S+/g,'').replace(/\s+/g,' ').trim();
const rawText=(value:unknown)=>String(value??'').trim();
const plot=(value:unknown)=>clean(value).split(/(?:In questo libro sono presenti|Content warning|Recension[ei]|Film|Serie TV|Prezzo|Acquista|Spedizione|Disponibil)/i)[0].replace(/\?\s+e\s+(?=[a-zà-ÿ])/g,'… e ').trim();
const detect=(value:string)=>{const code=value.replace(/[\s-]/g,'').toUpperCase();if(/^\d{4}-?\d{3}[\dX]$/.test(value)||/^\d{7}[\dX]$/.test(code))return'ISSN';if(/^(\d{9}[\dX]|\d{13})$/.test(code))return'ISBN';return'CODICE A BARRE';};
const names=(author:string)=>{const parts=author.split(/\s+/).filter(Boolean);return{authorFirstName:parts.slice(0,-1).join(' '),authorLastName:parts.at(-1)||author};};
const genres=(values:unknown)=>{const input=Array.isArray(values)?values:[values];const found=new Set<string>();for(const raw of input){const key=clean(raw).toLowerCase().replace(/[^a-z]/g,'');for(const[source,target]of Object.entries(literaryGenres))if(key.includes(source)&&target!=='Narrativa')found.add(target);}return[...found];};
const scalar=(value:unknown)=>Array.isArray(value)?value[0]:value;
const person=(value:unknown)=>{const item=scalar(value);return typeof item==='object'&&item?clean((item as Record<string,unknown>).name):clean(item);};
const titleCase=(value:string)=>value.split(/\s+/).map((word,index)=>{const lower=word.toLocaleLowerCase('it');return index>0&&/^(a|al|alla|con|da|dal|dalla|del|della|di|e|il|in|la|le|lo|per|un|una)$/.test(lower)?lower:lower.charAt(0).toLocaleUpperCase('it')+lower.slice(1)}).join(' ');
function titleInfo(value:unknown){const raw=clean(value);const match=raw.match(/\(([^()#]+?)(?:,\s*|\s+)#\s*(\d+)\)/i);const saga=match?.[1]?.trim()||'';const sagaOrder=match?Number(match[2]):null;const withoutSeries=raw.replace(/\s*\([^()]*#\s*\d+\)\s*/gi,' ').replace(/\.?\s*Ediz\.?\s*(?:italiana|italiano).*$/i,'').replace(/\s+/g,' ').trim();return{title:titleCase(withoutSeries),saga,sagaOrder};}
function italianDetails(html:string,requestedCode:string){const exact=html.match(new RegExp(`\\{[^{}]*"ean":"${requestedCode.replace(/[^0-9X]/gi,'')}"[^{}]*\\}`,'i'))?.[0]||'';let product:Record<string,unknown>={};try{product=JSON.parse(exact)}catch{}return{publisher:titleCase(clean(product.brand)),genres:genres(clean(product.division).split('>'))};}
function nodes(value:unknown):Record<string,unknown>[] {if(Array.isArray(value))return value.flatMap(nodes);if(!value||typeof value!=='object')return[];const obj=value as Record<string,unknown>;return[obj,...Object.values(obj).flatMap(nodes)];}
function jsonLd(html:string){const blocks=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];return blocks.flatMap((match)=>{try{return nodes(JSON.parse(match[1]));}catch{return[];}});}
function candidatesFrom(html:string,source:string,requestedCode:string,codeType:string):Candidate[]{const output:Candidate[]=[];const italian=italianDetails(html,requestedCode);for(const item of jsonLd(html)){const type=clean(item['@type']);if(!/(Book|Product)/i.test(type))continue;const info=titleInfo(item.name||item.headline);const author=person(item.author||item.creator||item.brand);if(!info.title||!author)continue;const date=clean(item.datePublished||item.releaseDate);const structuredSeries=typeof item.isPartOf==='object'&&item.isPartOf?clean((item.isPartOf as Record<string,unknown>).name):'';const imageValue=scalar(item.image);const coverUrl=typeof imageValue==='object'&&imageValue?rawText((imageValue as Record<string,unknown>).url):rawText(imageValue);const description=clean(item.description);const enrichedGenres=new Set([...(genres(item.genre||item.category).length?genres(item.genre||item.category):italian.genres)]);if(/\bspicy\b|contenuti sessuali espliciti/i.test(description))enrichedGenres.add('Spicy');output.push({title:info.title,author,...names(author),code:clean(item.isbn||item.gtin||item.sku||requestedCode),codeType,genres:[...enrichedGenres],publisher:person(item.publisher)||italian.publisher,publicationYear:Number(date.match(/\d{4}/)?.[0])||null,saga:structuredSeries||info.saga,sagaOrder:info.sagaOrder,prequel:'',sequel:'',coverUrl:coverUrl||null,plot:plot(description),notes:'',rating:0,isRead:false,inLibrary:false,lentTo:'',lentDate:'',source});}return output;}
async function page(url:string){try{const response=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; LibriDiCarta/1.0)'},signal:AbortSignal.timeout(9000)});return response.ok?await response.text():'';}catch{return'';}}
async function source(url:string,name:string,query:string,type:string){return candidatesFrom(await page(url),name,query,type);}
function merge(primary:Candidate,secondary:Candidate){return{...secondary,...primary,title:secondary.title.length<primary.title.length?secondary.title:primary.title,genres:primary.genres.length?primary.genres:secondary.genres,publisher:primary.publisher||secondary.publisher,publicationYear:primary.publicationYear||secondary.publicationYear,saga:primary.saga||secondary.saga,sagaOrder:primary.sagaOrder||secondary.sagaOrder,prequel:primary.prequel||secondary.prequel,sequel:primary.sequel||secondary.sequel,coverUrl:primary.coverUrl||secondary.coverUrl,plot:primary.plot||secondary.plot,source:`${primary.source} + ${secondary.source}`};}
async function neighbours(saga:string,order:number|null,author:string){if(!saga||!order)return{prequel:'',sequel:''};const html=await page(`https://www.goodreads.com/search?q=${encodeURIComponent(`${saga} ${author}`)}`);const titles=[...html.matchAll(/<img\s+alt="([^"]+)"\s+class="bookCover"/gi)].map(match=>titleInfo(match[1]));const pick=(wanted:number)=>titles.find(item=>item.saga.toLocaleLowerCase()===saga.toLocaleLowerCase()&&item.sagaOrder===wanted)?.title||'';return{prequel:order>1?pick(order-1):'',sequel:pick(order+1)};}
async function seriesFor(title:string,author:string){for(const query of [`${title} ${author}`,`${title.split(/\s+/)[0]} ${author}`]){const html=await page(`https://www.goodreads.com/search?q=${encodeURIComponent(query)}`);const meta=html.match(/<meta\s+property="og:title"\s+content="([^"]+)"/i)?.[1];const titles=[...(meta?[titleInfo(meta)]:[]),...[...html.matchAll(/<img\s+alt="([^"]+)"\s+class="bookCover"/gi)].map(match=>titleInfo(match[1]))];const found=titles.find(item=>item.title.toLocaleLowerCase()===title.toLocaleLowerCase()&&item.saga&&item.sagaOrder);if(found)return found;}return null;}

export async function GET(request:Request){const query=new URL(request.url).searchParams.get('q')?.trim()||'';if(!query)return Response.json({error:'Inserisci un codice'},{status:400});const type=detect(query);const normalized=query.replace(/[\s-]/g,'');const [goodreads,italian]=await Promise.all([source(`https://www.goodreads.com/search?q=${encodeURIComponent(query)}`,'Goodreads',query,type),source(`https://www.libreriauniversitaria.it/ricerca/query/${encodeURIComponent(normalized)}/gzuzqkrI_qOHGlQ966Pc-A`,'Libreria Universitaria',query,type)]);let results=goodreads.length&&italian.length?[merge(goodreads[0],italian[0]),...goodreads.slice(1),...italian.slice(1)]:[...goodreads,...italian];
  const title=goodreads[0]?.title||query;const story=await source(`https://app.thestorygraph.com/browse?search_term=${encodeURIComponent(title)}`,'The StoryGraph',query,type);if(results.length&&story.length)results=[merge(results[0],story[0]),...results.slice(1)];else if(!results.length)results=story;
  if(!results.length||results.some((item)=>!item.plot||!item.coverUrl||!item.publisher)){const fallbacks=await Promise.all([
    source(`https://www.ibs.it/search/?query=${encodeURIComponent(query)}`,'IBS',query,type),
    source(`https://www.lafeltrinelli.it/search?query=${encodeURIComponent(query)}`,'Feltrinelli',query,type),
    source(`https://www.mondadoristore.it/search/?g=${encodeURIComponent(query)}`,'Mondadori Store',query,type),
  ]);const additional=fallbacks.flat();if(results.length&&additional.length)results=[merge(results[0],additional[0]),...results.slice(1),...additional.slice(1)];else results=[...results,...additional];}
  if(results[0]){if(!results[0].saga||!results[0].sagaOrder){const found=await seriesFor(results[0].title,results[0].author);if(found)results[0]={...results[0],saga:found.saga,sagaOrder:found.sagaOrder};}const adjacent=await neighbours(results[0].saga,results[0].sagaOrder,results[0].author);results[0]={...results[0],...adjacent,...catalogCorrections[normalized]};}
  const seen=new Set<string>();results=results.filter((item)=>{const key=`${item.title.toLowerCase()}|${item.author.toLowerCase()}|${item.code}`;if(seen.has(key))return false;seen.add(key);return true;}).slice(0,8);
  return Response.json({codeType:type,candidates:results});}
